const PET_DATA = [
  {
    "name":"Dog",
    "price":5000,
    "image":"dog.png"
  },{
    "name":"Cat",
    "price":3000,
    "image":"cat.png"
  },
  {
    "name":"Ferret",
    "price":2000,
    "image":"ferret.png"
  },
  {
    "name":"Hedgehog",
    "price":500,
    "image":"hedgehog.png"
  },
  {
    "name":"Snake",
    "price":10000,
    "image":"snake.png"
  },
  {
    "name":"Fish",
    "price":100,
    "image":"fish.png"
  },
  {
    "name":"Lizard",
    "price":800,
    "image":"lizard.png"
  },
  {
    "name":"Parrot",
    "price":3200,
    "image":"parrot.png"
  },
  {
    "name":"Hamster",
    "price":200,
    "image":"hamster.png"
  },
  {
    "name":"Rabbit",
    "price":2000,
    "image":"rabbit.png"
  }
  
];