const PET_DATA = [
  {
    "name":"Dog",
    "price":2.99,
    "image":"dog.png"
  },{
    "name":"Cat",
    "price":4.99,
    "image":"cat.png"
  },
  {
    "name":"Ferret",
    "price":1.49,
    "image":"ferret.png"
  },
  {
    "name":"Hedgehog",
    "price":2.99,
    "image":"hedgehog.png"
  },
  {
    "name":"Snake",
    "price":9.49,
    "image":"snake.png"
  },
  {
    "name":"Fish",
    "price":4.49,
    "image":"fish.png"
  },
  {
    "name":"Lizard",
    "price":17.99,
    "image":"lizard.png"
  },
  {
    "name":"Parrot",
    "price":2.99,
    "image":"parrot.png"
  },
  {
    "name":"Hamster",
    "price":6.99,
    "image":"hamster.png"
  },
  {
    "name":"Rabbit",
    "price":6.99,
    "image":"rabbit.png"
  }
  
];